### ISSUE TITLE
[Bug] Server dies after specific actions.

### ISSUE THREAD

**Issue by frosthuuund** [Stardust-Labs-MC/Terralith#120]
### What Minecraft version(s) does this apply to?

1.21

### Project version

2.5.2

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Create a world with seed 3732439369605022534
Teleport yourself at 2816 320 5920
```
[13:46:03] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_60445(class_3898.java:647) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18857(class_3215.java:525) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:137) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8402(class_1937.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8497(class_1937.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8320(class_1937.java:374) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:751) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:959) ~[client-intermediary.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:142) ~[client-intermediary.jar:?]
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Requested chunk unavailable during world generation
	at net.minecraft.class_3233.method_8402(class_3233.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_16359(class_4538.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_4543.method_22393(class_4543.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_23753(class_4538.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_6792.method_38918(class_6792.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_6661.method_14452(class_6661.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39649(class_6796.java:48) ~[client-intermediary.jar:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:361) ~[client-intermediary.jar:?]
	at net.minecraft.class_9310.method_57610(class_9310.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_9770.method_60560(class_9770.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_60442(class_3898.java:632) ~[client-intermediary.jar:?]
	at net.minecraft.class_9761.method_60461(class_9761.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60428(class_9759.java:143) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60427(class_9759.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60432(class_9759.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60424(class_9759.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_60446(class_3898.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

### Additional context

With Concurrent Chunk Management Engine the game just crashes. Datapack is fine, its just Fabric Mod.

**Comment by catter1** [comment]
This was fixed in 2.5.3 - update and it should be fine.
